
services:
  db:
    image: postgres:17.6
    container_name: user_db
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5433:5432"   # port externe 5433 pour éviter les conflits avec ton PostgreSQL local
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: imane@imane.com
      PGADMIN_DEFAULT_PASSWORD: imane@2002
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
